### ISSUE TITLE
Should the trapped check be after a move?

### ISSUE THREAD

**Issue by SrivastavaAnubhav** [ljvmiranda921/gym-lattice#24]
I feel like the trapped check would be better to put after a move has been inserted into self.state. Otherwise there's no way to tell from the top-level program that we're trapped.

Right now I think we force the algorithm to take an extra step before it realizes "Hey, I was trapped after the previous move". It would be better to end the simulation immediately. Again, I'm willing to take this up if that's ok with you.

**Comment by ljvmiranda921** [comment]
Hmm, I think you're right! It's unfortunate I wasn't able to expose that trap check after the move. 
Sure, I don't mind! Thanks a lot for taking point on this! @SrivastavaAnubhav
